---
  - hosts: wordpress
    handlers: 
      - name: restart apache
        service:
          name: apache2
          state: restarted
    become: yes

    tasks:
    - name: 'Adicionando Repositorio php8'
      ansible.builtin.apt_repository:
        repo: 'ppa:ondrej/php'
      become: yes
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      become: yes
    - name: 'Instala pacotes do sistema operacional'
      apt: 
        name: 
          - php8.1
          - apache2
          - libapache2-mod-php8.1
          - php8.1-gd
          - libssh2-1-dev
          - php8.1-mcrypt
          - php8.1-mysql
        state: latest
      become: yes
    
    - name: 'Download WordPress'
      get_url:
        url: 'https://wordpress.org/latest.tar.gz'
        dest: '/tmp/wordpress.tar.gz'
    
    - name: 'Descompactando o WordPress'
      ansible.builtin.unarchive:
        src: '/tmp/wordpress.tar.gz'
        dest: '/var/www'
        remote_src: yes
      become: yes

    - name: 'Cria o wp-config usando o wp-config-sample'
      copy:  
        src: '/var/www/wordpress/wp-config-sample.php'
        dest: '/var/www/wordpress/wp-config.php'
        remote_src: yes
      become: yes
    
    - name: 'Configura o wp-config com as entradas do banco de dados'
      replace:
        path: '/var/www/wordpress/wp-config.php'
        regexp: "{{ item.regex }}"
        replace: "{{ item.value }}"
      with_items:
        - { regex: 'database_name_here', value: 'wordpress_db' }
        - { regex: 'username_here', value: 'wordpress_user' }
        - { regex: 'password_here', value: '123' }
        - { regex: 'localhost', value: '192.168.15.10'}
      become: yes

    - name: 'Configura o apache para servir Wordpress'
      copy:  
        src: '../000-default.conf'
        dest: '/etc/apache2/sites-available/000-default.conf'
      become: yes
      notify:
        - restart apache

#####mysqlserver

  - hosts: mysqlserver
    handlers:
    - name: restart mysql
      service:
        name: mysql
        state: restarted
      become: yes

    tasks:
    - name: 'Instalar MySQL Server'
      apt:
        update_cache: yes
        cache_valid_time: 3600 #1 hora
        name: ["mysql-server-5.7", "python3-mysqldb"]
        state: latest
      become: yes
    
    - name: 'Cria o banco do MySQL'
      mysql_db: 
        login_user: root
        name: wordpress_db
        state: present
      become: yes

    - name: 'Criar usuario no MySQL'
      mysql_user:
        login_user: root
        name: wordpress_user
        password: 123
        priv: 'wordpress_db.*:ALL'
        host: '192.168.15.11'
        state: present
      become: yes

    - name: 'Copiar arquivo mysqld.cnf'
      copy:
        src: ../mysqld.cnf
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
        owner: root
        group: root
        mode: 0644
      become: yes
      notify:
        - restart mysql